language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"

# Use faster Docker architecture on Travis. (http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)
sudo: false
